syntax = "proto3";

package sc.internal.services.entitlement.v2;

import "sc/external/services/entitygraph/v1/types.proto";
import "sc/external/services/entitlement/v2/types.proto";
import "sc/internal/services/entity_creator/v2/types.proto";
import "google/protobuf/timestamp.proto";

message ReconcileAccountCommand {
  string account_urn = 1;
  string player_urn = 2;
  string log_message = 3;
  bool force_reconcile_ltp = 4;
}

message ReconcileAccountResult {
  uint32 new_entitlements_count = 1;
}

message CurrentStowContext {
  bool is_stowed = 1;
  oneof location {
    string shard_id = 2;
    string inventory_id = 3;
  }
  uint32 class_guid_crc = 4;
}

message CreateEntitlementPayload {
  string urn = 1;
  string source_urn = 2;
  .sc.external.services.entitlement.v2.EntitlementSourceType source_type = 3;
  .sc.external.services.entitlement.v2.EntitlementStatus status = 4;
  string entity_class_guid = 5;
  uint64 entity_geid = 6;
  uint64 player_id = 7;
  .sc.external.services.entitlement.v2.EntityConfiguration web_customization = 8;
  .google.protobuf.Timestamp rental_expiry = 9;
  .sc.external.services.entitlement.v2.EntitlementMetadata metadata = 10;
  .sc.internal.services.entitlement.v2.CurrentStowContext current_stow_context = 11;
}

message CreateEntitlementCommand {
  repeated .sc.internal.services.entitlement.v2.CreateEntitlementPayload entitlements = 1;
}

message CreateAndDeliverEntitlementCommand {
  repeated .sc.internal.services.entitlement.v2.CreateEntitlementPayload entitlements = 1;
  .sc.external.services.entitygraph.v1.InventoryDestination inventory_destination = 2;
  string root_entitlement_urn = 3;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 4;
  string fallback_inventory_id = 5;
}

message DeliverEntitlementCommand {
  uint64 player_id = 1;
  .sc.external.services.entitygraph.v1.InventoryDestination inventory_destination = 2;
  string root_entitlement_urn = 3;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 4;
  string fallback_inventory_id = 5;
}

message ClaimEntitlementCommand {
  uint64 player_id = 1;
  .sc.external.services.entitygraph.v1.InventoryDestination inventory_destination = 2;
  string root_entitlement_urn = 3;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 4;
  string fallback_inventory_id = 5;
}

message UpsertSnapshotsCommand {
  uint64 player_id = 1;
  string entitlement_urn = 2;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 3;
  repeated .sc.external.services.entitlement.v2.SnapshotRecord snapshots = 4;
  repeated .sc.internal.services.entitlement.v2.CreateEntitlementPayload to_be_created_entitlements = 5;
}

message ClearSnapshotsCommand {
  uint64 player_id = 1;
  string entitlement_urn = 2;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 3;
}

message RevokeEntitlementCommand {
  uint64 player_id = 1;
  repeated string entitlement_urns = 2;
  bool brick_entities = 3;
}

message RevokeAllPlayerEntitlementsCommand {
  uint64 player_id = 1;
  string log_message = 2;
}

message RestoreEntitlementCommand {
  uint64 player_id = 1;
  string root_entitlement_urn = 2;
  .sc.external.services.entitlement.v2.SnapshotSlotId snapshot_slot_id = 3;
  repeated .sc.internal.services.entity_creator.v2.MissingItemStructure missing_item_structures = 4;
  string shard_id = 5;
}

